version: "3.7"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=splitter"
      - "POSTGRES_USER=splitter"
      - "POSTGRES_PASSWORD=splitter34"